### PR TITLE
adding notes to make startup less confusing

### PR DESCRIPTION
**Pull request by logyball**
added a small check to make sure you're running from the root directory to more closely align with the previous steps (tests are run from the root dir).  Updated readme, added src to the path join.

### CODE REVIEW

**Comment by logyball** [comment]
~~also I could just put this in the readme (ie "make sure main.py to run from src/") rather than actually changing the code~~

I think that just changing the readme is not an option, because running the tests must happen in the root directory, and currently the behave tests hang infinitely.  This solves that problem, but exposes a failing test (which I could investigate on another branch).

**Comment by samgomena** [comment]
Yah. I think the tests are kinda fubared after Martins changes in the previous PR. Though, if you want to take a look at them feel free!

**Review by samgomena — APPROVED** [review]

**Comment by logyball** [comment]
@samgomena Ok I will investigate in a new branch

**Comment by lixphilosophy** [comment]
Looks good.

**Review by lixphilosophy — APPROVED** [review]
Looks good.

**Comment by logyball** [comment]
@samgomena @lixphilosophy  seems like I can't merge due to the travis checks.  I could comment the integration (behave) tests out in the .travis.yml to merge this branch or I could investigate in this branch, or can one of you merge? (I'm guessing you have admin credentials that I don't)

**Comment by lixphilosophy** [comment]
When I was working on the last PR, the test would always fail after this [commit](https://github.com/deepmarket/PLUTO/pull/59/commits/d1699b9fc2f278a939e69aeaba9076f227da4a47). I track the [log](https://travis-ci.org/deepmarket/PLUTO/jobs/561197996), and the test just exited for no reason:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by samgomena** [comment]
@loganballard I think fixing the tests should be done in a separate branch that focuses solely on that. For now, I'm going to say it's OK that the tests fail under the assumption that we'll be fixing them soonish.

**Pull request merged**
